% BoB Sensor GUI
% July 2020
 
function ex02_crb_gui()
 
    angle1 = 20;
    variance1 = 1;
    angle2 = 80;
    variance2 = 1;
    angle3 = 135;
    variance3 = 1000;
    
    theta1=3;
    theta2=4;
    % Create a window for the GUI
    window = figure('Color', [0.9255 0.9137 0.8471],...
                    'Name', 'PositionCRB GUI',...
                    'DockControl', 'off',...
                    'Units', 'Pixels',...
                    'Position', [100 50 600 800]);
 
    % Add axes on left side for time domain plot
    ax1 = axes('Parent', window,...
                    'Units', 'normalized',...
                    'Position', [0.07 0.47 0.8 0.5]);
    % Add "Angle" slider control to window
    angle1_slider = uicontrol('Parent', window,...
                    'Style', 'slider',...
                    'Units', 'normalized',...
                    'Position', [0.2 0.35 0.6 0.08],...
                    'Min', 0,...
                    'Max', 360,...
                    'Value', angle1,...
                    'Callback', @updateGraph);
    % Add "Angle" edit control to window
    angle1_edit = uicontrol('Parent', window,...
                    'Style', 'edit',...
                    'FontSize', 18,...
                    'Units', 'normalized',...
                    'Position', [0.82 0.39 0.12 0.05]);
    % Add "Angle" label control to window
    angle1_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'String', 'Angle1:',...
                    'FontSize', 18,...
                    'Units', 'normalized',...
                    'Position', [0.02 0.39 0.12 0.05]);               
    % Add "Variance" slider control to window
    variance1_slider = uicontrol('Parent', window,...
                    'Style', 'slider',...
                    'Units', 'normalized',...
                    'Position', [0.2 0.30 0.6 0.08],...
                    'Min', log10(0.01),...
                    'Max', log10(10000),...
                    'Value', log10(variance1),...
                    'Callback', @updateGraph);
    % Add "Variance" edit control to window
    variance1_edit = uicontrol('Parent', window,...
                    'Style', 'edit',...
                    'FontSize', 18,...
                    'Units', 'normalized',...
                    'Position', [0.82 0.34 0.12 0.05]); 
    % Add "Variance" label control to window
    variance1_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'String', 'Variance1:',...
                    'FontSize', 18,...
                    'Units', 'normalized',...
                    'Position', [0.02 0.34 0.15 0.05]);
    % Add "Angle" slider control to window
    angle2_slider = uicontrol('Parent', window,...
                    'Style', 'slider',...
                    'Units', 'normalized',...
                    'Position', [0.2 0.25 0.6 0.08],...
                    'Min', 0,...
                    'Max', 360,...
                    'Value', angle2,...
                    'Callback', @updateGraph);
    % Add "Angle" edit control to window
    angle2_edit = uicontrol('Parent', window,...
                    'Style', 'edit',...
                    'FontSize', 18,...
                    'Units', 'normalized',...
                    'Position', [0.82 0.29 0.12 0.05]);
    % Add "Angle" label control to window
    angle2_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'String', 'Angle2:',...
                    'FontSize', 18,...
                    'Units', 'normalized',...
                    'Position', [0.02 0.29 0.12 0.05]);
                
    % Add "Variance" slider control to window
    variance2_slider = uicontrol('Parent', window,...
                    'Style', 'slider',...
                    'Units', 'normalized',...
                    'Position', [0.2 0.20 0.6 0.08],...
                    'Min', log10(0.01),...
                    'Max', log10(10000),...
                    'Value', log10(variance2),...
                    'Callback', @updateGraph);
    % Add "Variance" edit control to window
    variance2_edit = uicontrol('Parent', window,...
                    'Style', 'edit',...
                    'FontSize', 18,...
                    'Units', 'normalized',...
                    'Position', [0.82 0.24 0.12 0.05]); 
    % Add "Variance" label control to window
    variance2_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'String', 'Variance2:',...
                    'FontSize', 18,...
                    'Units', 'normalized',...
                    'Position', [0.02 0.24 0.15 0.05]);
    % Add "Angle" slider control to window
    angle3_slider = uicontrol('Parent', window,...
                    'Style', 'slider',...
                    'Units', 'normalized',...
                    'Position', [0.2 0.15 0.6 0.08],...
                    'Min', 0,...
                    'Max', 360,...
                    'Value', angle3,...
                    'Callback', @updateGraph);
    % Add "Angle" edit control to window
    angle3_edit = uicontrol('Parent', window,...
                    'Style', 'edit',...
                    'FontSize', 18,...
                    'Units', 'normalized',...
                    'Position', [0.82 0.19 0.12 0.05]);
    % Add "Angle" label control to window
    angle3_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'String', 'Angle3:',...
                    'FontSize', 18,...
                    'Units', 'normalized',...
                    'Position', [0.02 0.19 0.12 0.05]);
                
    % Add "Variance" slider control to window
    variance3_slider = uicontrol('Parent', window,...
                    'Style', 'slider',...
                    'Units', 'normalized',...
                    'Position', [0.2 0.10 0.6 0.08],...
                    'Min', log10(0.01),...
                    'Max', log10(10000),...
                    'Value', log10(variance3),...
                    'Callback', @updateGraph);
    % Add "Variance" edit control to window
    variance3_edit = uicontrol('Parent', window,...
                    'Style', 'edit',...
                    'FontSize', 18,...
                    'Units', 'normalized',...
                    'Position', [0.82 0.14 0.12 0.05]); 
    % Add "Variance" label control to window
    variance3_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'String', 'Variance3:',...
                    'FontSize', 18,...
                    'Units', 'normalized',...
                    'Position', [0.02 0.14 0.15 0.05]);
                

    % Call the slider callback function once when the
    % program first runs to make sure that the plots
    % appear immediately (without the user clicking anything)
    updateGraph()
 
   
    % Callback funuction for both slider controls
    function updateGraph(hObj, event)
        alpha=zeros(3,1);
        sigma2=zeros(3,1);    
        alpha(1) = get(angle1_slider, 'Value');
        sigma2(1) = 10^(get(variance1_slider, 'Value'));
        alpha(2) = get(angle2_slider, 'Value');
        sigma2(2) = 10^(get(variance2_slider, 'Value'));
        alpha(3) = get(angle3_slider, 'Value');
        sigma2(3) = 10^(get(variance3_slider, 'Value'));
        set(angle1_edit, 'String', alpha(1))
        set(variance1_edit, 'String', sigma2(1))
        set(angle2_edit, 'String', alpha(2))
        set(variance2_edit, 'String', sigma2(2))
        set(angle3_edit, 'String', alpha(3))
        set(variance3_edit, 'String', sigma2(3))
 
        I=zeros(2,2);
        for n = 1:3
            cn = cos(pi/180*alpha(n)); 
            sn = sin(pi/180*alpha(n));
            I = I + 1/sigma2(n)*[cn^2 cn*sn; cn*sn sn^2];
        end
        
        % Plot covariance ellipsoid
        C = inv(I);    
        phiv = (linspace(0,2*pi,100))';
        ellips = ([cos(phiv) sin(phiv)])*chol(C);
        plot(ax1,theta1,theta2,'b*');
        title('Positioning - Cramer Rao Bound','Fontsize',16)
        hold on
        plot(ax1,theta1+ellips(:,1),theta2+ellips(:,2),'r-')
        set(ax1, 'xlim', [-10 10], 'ylim', [-10 10]);
        for n = 1:3
            plot(ax1,[0 15*cos(pi/180*alpha(n))],[0 15*sin(pi/180*alpha(n))],'k-')
        end
        hold off

    end
 
end